name: CI
on:
  workflow_dispatch:
jobs:
  
  Pre_Build_Tasks:
    runs-on: ubuntu-latest
    
    services:
      node:
        image: node
#       gradle: 
#         image: gradle
#       dotnet: 
#         image: maven

    steps:
      - uses: actions/checkout@v1

      - name: Cache the packages
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
        
      - name: Use Java
        uses: actions/setup-java@v1
        with:
          java-version: 14
        

      
  Build:
    needs: Pre_Build_Tasks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build Applicaition
        run: |
          mvn -B package --file pom.xml
          

  Unit_Tests:
    needs: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build Applicaition
        run: |
          mvn -B package --file pom.xml
      - name: Upload Code Coverage Artifact
        uses: actions/upload-artifact@v1
        with: 
          name: code_quality_test
          path: test
      
      
  Code_Quality_Scan:
    needs: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Code Quality
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: |
          
          mvn sonar:sonar --batch-mode --quiet -Dsonar.host.url=http://localhost:9000 -Dsonar.token=SONAR.TOKEN
        continue-on-error: true
        
          
  Publish_Artifact:
    needs: [Build,Code_Quality_Scan]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build Applicaition
        run: |
          mvn -B package --file pom.xml
      - name: Create 
        run: |
          mkdir stg
          cp target/*jar-with-dependencies.jar stg
      - name: Publish Artifact
        uses: actions/upload-artifact@v1
        with:
          name: build_artifact
          path: stg
  
  Create_Deployment_Package:
    
    needs: Publish_Artifact
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: |
          echo "Create_Deployment_Package"

  Tag_Deployment_Artifact:
    
    needs: Create_Deployment_Package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: |
          echo "Tag_Deployment_Artifact"
