on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Use Java
        uses: actions/setup-java@v1
        with:
          java-version: 14

      - name: Build Applicaition
        run: mvn -B package --file pom.xml
