name: CI
on:
  workflow_dispatch:
jobs:
  
  Pre_Build_Tasks:
    runs-on: ubuntu-latest
    
    services:
      node:
        image: node
#       gradle: 
#         image: gradle
#       dotnet: 
#         image: maven

    steps:
      - uses: actions/checkout@v1

      - name: Cache the packages
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
        
      - name: Use Java
        uses: actions/setup-java@v1
        with:
          java-version: 14
        
          

  Build_Test:
    needs: Pre_Build_Tasks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build Applicaition
        run: |
          mvn -B package --file pom.xml
          mkdir test
          cp target/jacoco.exec test
      - name: Upload Code Coverage Artifact
        uses: actions/upload-artifact@v1
        with: 
          name: code_quality_test
          path: test
          
  Dockerized_Quality_Scan:
    needs: Build_Test
    runs-on: ubuntu-latest
    steps:
      - name: Dockerized sonar scan testing
        uses: SonarSource/sonarqube-scan-action@v1
        with: 
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      
  Code_Quality_Scan:
    needs: Build_Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Code Quality
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: |
          
          mvn sonar:sonar --batch-mode --quiet -Dsonar.host.url=http://localhost:9000 -Dsonar.token=SONAR.TOKEN
        continue-on-error: true
        
  Vercode_Pipeline_Scan:
    needs: Code_Quality_Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: |
          echo "Vercode pipeline scane stage"
        
  Vercode_SCA_Scan:
    needs: Vercode_Pipeline_Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: |
          echo "Vercode SCA SCAN"   
          
  Build_publish_Docker:
    name: Publish to Docker Hub
    runs-on: ubuntu-latest
    needs: [Code_Quality_Scan]

    steps:
      - uses: actions/checkout@v2
#       - name: Login to Docker Hub
#         run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Container image
        run: docker build -t ${{ secrets.DOCKER_REPO }}:latest .
#       - name: Publish Docker image
#         run: docker push ${{ secrets.DOCKER_REPO }}
    
  
  Publish_Artifact:
    needs: Code_Quality_Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build Applicaition
        run: |
          mvn -B package --file pom.xml
      - name: Create 
        run: |
          mkdir stg
          cp target/*jar-with-dependencies.jar stg
      - name: Publish Artifact
        uses: actions/upload-artifact@v1
        with:
          name: build_artifact
          path: stg
  
  Create_Deployment_Package:
    
    needs: Publish_Artifact
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: |
          echo "Create_Deployment_Package"

  Tag_Deployment_Artifact:
    
    needs: Create_Deployment_Package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: |
          echo "Tag_Deployment_Artifact"
